<string>            ::= <atom> (<union> | <branch> | <split>)*
<union>             ::= <bond>? ( <cut> | <string> )
<branch>            ::= "(" ( "." | <bond> )? <string> ")"
<split>             ::= "." <string>
<atom>              ::= <shortcut> | <selected-shortcut> | "*" | <bracket>
<bracket>           ::= "[" <isotope>?
                         ( <element> | <selected-element> | "*" )
                         <stereodescriptor>? <virtual-hydrogen>? <charge>?
                         <extension>? "]"
<isotope>           ::= <non-zero> <digit>? <digit>?
<virtual-hydrogen>  ::= "H" <digit>?
<charge>            ::= ( "+" | '-' ) <non-zero>?
<extension>         ::= ":" <hex>? <hex>? <hex>? <hex>
<cut>               ::= <digit> | "%" <non-zero> <digit>
<stereodescriptor>  ::= "@" "@"?
<shortcut>          ::= "C"
<selected-shortcut> ::= "c"
<element>           ::= "C"
<selected-element>  ::= "c"
<bond>              ::= "-" | "=" | "#" | "$" | "/" | "\\"
<non-zero>          ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<digit>             ::= "0" | <non-zero>
<hex>               ::= <digit> | "a" | "b" | "c" | "d" | "e" | "f"