const {Diagram, HorizontalChoice, Sequence, Terminal, Choice , Optional, NonTerminal } = require('../../lib/railroad-diagrams.js');

module.exports = Diagram(
  HorizontalChoice(
    Sequence(
      Terminal('A'),
      Choice(
        0,
        Terminal('c'),
        Terminal('g'),
        Terminal('l'),
        Terminal('m'),
        Terminal('r'),
        Terminal('s'),
        Terminal('t'),
        Terminal('u')
      )
    ),
    Sequence(
       Terminal('B'),
        Optional(
          Choice(
            0,
            Terminal('a'),
            Terminal('e'),
            Terminal('h'),
            Terminal('i'),
            Terminal('k'),
            Terminal('r')
          )
        )
    ),
    Sequence(
      Terminal('C'),
      Optional(
        Choice(
          0,
          Terminal('a'),
          Terminal('d'),
          Terminal('e'),
          Terminal('f'),
          Terminal('l'),
          Terminal('m'),
          Terminal('n'),
          Terminal('o')
        )
      )
    ),
    NonTerminal('...')
  )
)